/*
 * gen-golden.mjs — emits the values that AgentiaCore and build-page.mjs must
 * agree on, byte for byte.
 *
 * The Swift test suite reads the generated file and compares. If either
 * implementation drifts, `swift test` fails rather than the difference going
 * unnoticed until a page renders wrongly.
 *
 * Regenerate after touching shell.js or the CSP:
 *     node tools/gen-golden.mjs
 *
 * Note on scope: bootstrap JSON is deliberately not compared byte for byte.
 * Swift's JSONEncoder sorts keys and JSON.stringify preserves insertion order,
 * so the two differ textually while parsing to the same object. What must match
 * is the "</script" neutralisation rule, which is checked separately.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import {
  ROOT, Profile, shellScript, shellScriptHash, contentSecurityPolicy,
  escapeForHTMLText, neutraliseClosingScriptTags, displayCSS, substitute,
} from "./webtest/build-page.mjs";

const HERE = dirname(fileURLToPath(import.meta.url));
const OUT_DIR = join(ROOT, "Tests", "AgentiaCoreTests", "Fixtures");

const hash = shellScriptHash();

const golden = {
  _comment:
    "Generated by tools/gen-golden.mjs. Do not edit by hand; run the script.",
  shellScriptSHA256: hash,
  shellScriptByteLength: Buffer.byteLength(shellScript(), "utf8"),
  contentSecurityPolicy: {
    markdown: contentSecurityPolicy(Profile.markdown, hash),
    htmlArtifact: contentSecurityPolicy(Profile.htmlArtifact, hash),
  },
  // Expectations are produced by the JS implementation rather than written
  // by hand, so the golden file cannot disagree with the code that generated
  // the pages the browser suite already verified.
  htmlTextEscaping: [
    "plain",
    "a & b",
    "<script>",
    "quote\" and 'single'",
    "&amp;",
    "Ünïcode — ok",
  ].map((input) => ({ input, expected: escapeForHTMLText(input) })),

  closingScriptNeutralisation: [
    '{"a":"</script>"}',
    '{"a":"</SCRIPT >"}',
    '{"a":"</ScRiPt"}',
    '{"a":"</scr"}',
    '{"a":"no tags"}',
    '{"a":"</script></script>"}',
    // Moves the script-data tokenizer into the double-escaped state, where the
    // block's own </script> no longer closes it.
    '{"a":"<!--<script>"}',
    '{"a":"<!--<SCRIPT"}',
  ].map((input) => ({ input, expected: neutraliseClosingScriptTags(input) })),

  // The reader's font scale. Both implementations clamp to the same range and
  // format to four decimals — a scale in scientific notation would not parse as
  // CSS, and the page would silently render at the theme's size. Includes the
  // print reset, whose placement inside this declaration is what makes it win.
  displayCSS: [0.7, 1, 1.3, 2, 12, 0.01, -5, 1.0001]
    .map((input) => ({ input, expected: displayCSS(input) })),

  // Placeholder substitution. Non-reentrant by construction and tolerant of
  // unknown tokens, because a document about Handlebars or Jinja is an ordinary
  // thing for an agent to write.
  substitution: [
    { template: "a {{X}} b", values: { X: "1" } },
    { template: "{{X}}{{Y}}", values: { X: "{{Y}}", Y: "2" } },
    { template: "{{UNKNOWN}}", values: { X: "1" } },
    { template: "{{ X }}", values: { X: "1" } },
    { template: "{{}}", values: { X: "1" } },
    { template: "{{TOO_LONG_A_NAME_TO_BE_A_TOKEN_AT_ALL_HERE}}", values: {} },
    { template: "unterminated {{X", values: { X: "1" } },
    { template: "{{x}}", values: { X: "1" } },
  ].map(({ template, values }) => ({
    template, values, expected: substitute(template, values),
  })),
};

mkdirSync(OUT_DIR, { recursive: true });
const path = join(OUT_DIR, "golden.json");
writeFileSync(path, JSON.stringify(golden, null, 2) + "\n");

console.log(`wrote ${path}`);
console.log(`  shell.js sha256 : ${hash}`);
console.log(`  markdown CSP    : ${golden.contentSecurityPolicy.markdown.slice(0, 60)}…`);
